# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Global
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
timezone: Asia/Taipei
encoding: UTF-8
paginate: 5


# Site
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ssdoz2sk.github.com" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <!--more-->

# Posts
title: Niangko 資工雜記
description: 'Niangko 在資工所學紀錄'
lang: zh_TW
author: ssdoz2sk
email: mybalance22@gmail.com
github_username:  ssdoz2sk

social:
  name: Jimmy Chang
  links: https://github.com/ssdoz2sk

# Tags
tag_page_layout: tag_page
tag_page_dir: tag

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
